In [14]:
import pandas as pd
from datetime import timedelta

In [4]:
selected_student = 80

context = pd.read_excel('context/Assessment_Information.xlsx')
context = context[context['student_id'] == selected_student]

context.head()

,student_id,question_id,answer,date,duration,option_selected,Topic,Subtopic,Lecturer_level,Algorithm_level,Typology
17046,80,142,1,2024-01-15T16:37:50.000Z,NaN,NaN,Differentiation,Derivatives,1,1,Admin
17047,80,94,1,2024-01-15T16:37:50.000Z,NaN,NaN,Differentiation,Derivatives,2,1,Admin
17048,80,734,0,2024-01-15T16:37:50.000Z,NaN,NaN,Differentiation,Derivatives,3,4,Admin
17049,80,274,1,2024-01-15T16:37:50.000Z,NaN,NaN,Differentiation,Derivatives,2,1,Admin
17050,80,721,0,2024-01-15T16:37:50.000Z,NaN,NaN,Differentiation,Derivatives,3,4,Admin

In [17]:
context['date'] = pd.to_datetime(context['date'])
last_interaction = context['date'].max()
print(last_interaction)

display(context)
step_1 = timedelta(days=15)
step_2 = timedelta(days=30)
step_3 = timedelta(days=60)

context['lapse_category'] = pd.cut(context['days_since_last_interaction'],
                                   bins=[-1, step_1.days, step_2.days, step_3.days, float('inf')],
                                   labels=['0-15 days', '16-30 days', '31-60 days', '60+ days'])
display(context)
print(context['lapse_category'].value_counts())

2025-01-14 15:58:38+00:00

,student_id,question_id,answer,date,duration,option_selected,Topic,Subtopic,Lecturer_level,Algorithm_level,Typology,days_since_last_interaction,lapse_category
17046,80,142,1,2024-01-15 16:37:50+00:00,NaN,NaN,Differentiation,Derivatives,1,1,Admin,364,60+ days
17047,80,94,1,2024-01-15 16:37:50+00:00,NaN,NaN,Differentiation,Derivatives,2,1,Admin,364,60+ days
17048,80,734,0,2024-01-15 16:37:50+00:00,NaN,NaN,Differentiation,Derivatives,3,4,Admin,364,60+ days
17049,80,274,1,2024-01-15 16:37:50+00:00,NaN,NaN,Differentiation,Derivatives,2,1,Admin,364,60+ days
17050,80,721,0,2024-01-15 16:37:50+00:00,NaN,NaN,Differentiation,Derivatives,3,4,Admin,364,60+ days
...,...,...,...,...,...,...,...,...,...,...,...,...,...
19766,80,575,0,2025-01-14 15:58:14+00:00,NaN,NaN,Analytic Geometry,NaN,5,1,Admin,0,0-15 days
19767,80,1742,0,2025-01-14 15:58:23+00:00,NaN,NaN,Analytic Geometry,NaN,5,1,Admin,0,0-15 days
19768,80,561,-1,2025-01-14 15:58:27+00:00,NaN,NaN,Analytic Geometry,NaN,5,1,Admin,0,0-15 days
19769,80,1740,1,2025-01-14 15:58:31+00:00,NaN,NaN,Analytic Geometry,NaN,4,1,Admin,0,0-15 days
19770,80,558,0,2025-01-14 15:58:38+00:00,NaN,NaN,Analytic Geometry,NaN,3,2,Admin,0,0-15 days

,student_id,question_id,answer,date,duration,option_selected,Topic,Subtopic,Lecturer_level,Algorithm_level,Typology,days_since_last_interaction,lapse_category
17046,80,142,1,2024-01-15 16:37:50+00:00,NaN,NaN,Differentiation,Derivatives,1,1,Admin,364,60+ days
17047,80,94,1,2024-01-15 16:37:50+00:00,NaN,NaN,Differentiation,Derivatives,2,1,Admin,364,60+ days
17048,80,734,0,2024-01-15 16:37:50+00:00,NaN,NaN,Differentiation,Derivatives,3,4,Admin,364,60+ days
17049,80,274,1,2024-01-15 16:37:50+00:00,NaN,NaN,Differentiation,Derivatives,2,1,Admin,364,60+ days
17050,80,721,0,2024-01-15 16:37:50+00:00,NaN,NaN,Differentiation,Derivatives,3,4,Admin,364,60+ days
...,...,...,...,...,...,...,...,...,...,...,...,...,...
19766,80,575,0,2025-01-14 15:58:14+00:00,NaN,NaN,Analytic Geometry,NaN,5,1,Admin,0,0-15 days
19767,80,1742,0,2025-01-14 15:58:23+00:00,NaN,NaN,Analytic Geometry,NaN,5,1,Admin,0,0-15 days
19768,80,561,-1,2025-01-14 15:58:27+00:00,NaN,NaN,Analytic Geometry,NaN,5,1,Admin,0,0-15 days
19769,80,1740,1,2025-01-14 15:58:31+00:00,NaN,NaN,Analytic Geometry,NaN,4,1,Admin,0,0-15 days
19770,80,558,0,2025-01-14 15:58:38+00:00,NaN,NaN,Analytic Geometry,NaN,3,2,Admin,0,0-15 days

lapse_category
60+ days      410
16-30 days     20
0-15 days      15
31-60 days      0
Name: count, dtype: int64